<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Promotion.Core.Contracts/Promotion.Core.Contracts.csproj" />
    <ProjectReference Include="../Promotion.Core/Promotion.Core.csproj" />
    <ProjectReference Include="../Promotion.Data.MySql/Promotion.Data.MySql.csproj" />
  </ItemGroup>
</Project>
